version: '2'
services:
  cloudant:
    image: ibmcom/couchdb3:latest
    container_name: cloudant-testdb
    restart: always
    privileged: true
    hostname: cloudant
    ports:
      - "8080:5984"
    expose:
      - "5984"
    volumes:
      - cloudant-testdb:/srv
    mem_limit: 256M
    network_mode: bridge
volumes:
    cloudant-testdb:
